[package]
name = "book-examples"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
publish = false
version = "0.0.0"

readme = "README.md"
license = "MIT"

[dev-dependencies]
rand = "0.8.5"
relm4 = "0.5.0-rc.2"
relm4-components = "0.5.0-rc.2"
tokio = { version = "1.9", features = ["rt", "macros", "time", "rt-multi-thread", "sync"] }
tracker = "0.1.1"
